-- Auto-generated by generate_mock_data.js
-- Estimated USD per token using public standard API rates and an 80% input / 20% output mix.
-- This is a blended estimate; usage records do not split token types.

INSERT INTO billing (model, per_token_cost) VALUES
('claude-haiku-5.5', 0.00000018),
('claude-sonnet-5.5', 0.00000360),
('claude-opus-5.5', 0.00000720),
('gpt-5', 0.00000300),
('gpt-5-codex', 0.00000420),
('gpt-5-mini', 0.00000060),
('gemini-2.5-pro', 0.00000300),
('gemini-2.5-flash', 0.00000074);
