-- Auto-generated by generate_mock_data.js
-- 8 models (illustrative blended USD per token)

INSERT INTO billing (model, per_token_cost) VALUES
('claude-haiku-5.5', 0.000002),
('claude-sonnet-5.5', 0.000009),
('claude-opus-5.5', 0.00003),
('gpt-5', 0.000006),
('gpt-5-codex', 0.000007),
('gpt-5-mini', 0.0000012),
('gemini-2.5-pro', 0.0000065),
('gemini-2.5-flash', 0.0000015);
