-- Auto-generated by generate_mock_data.js
-- 15 departments (dept_head_employee_id is linked in 06_link_heads.sql)

INSERT INTO departments (id, name, dept_head_employee_id, min_limit, max_limit) VALUES
(1, 'Core Engineering', NULL, 243000000, 243000000),
(2, 'Platform & Infrastructure', NULL, 255500000, 255500000),
(3, 'Mobile Engineering', NULL, 147500000, 161000000),
(4, 'Data Science & ML', NULL, 165500000, 165500000),
(5, 'Quality Engineering', NULL, 128000000, 128000000),
(6, 'Security Engineering', NULL, 82000000, 82000000),
(7, 'IT Operations', NULL, 99500000, 106000000),
(8, 'Product Management', NULL, 61000000, 67500000),
(9, 'Design', NULL, 49500000, 49500000),
(10, 'Sales', NULL, 68500000, 68500000),
(11, 'Marketing', NULL, 46000000, 46000000),
(12, 'Customer Success', NULL, 50500000, 50500000),
(13, 'Finance', NULL, 42500000, 42500000),
(14, 'Human Resources', NULL, 36500000, 36500000),
(15, 'Legal & Compliance', NULL, 29000000, 29000000);
SELECT setval('departments_id_seq', (SELECT MAX(id) FROM departments));
